<a href="https://colab.research.google.com/github/camila251/Aula_Senai/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(1)

In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5
print(w1)
print(w2)
print(w3)

0.3
0.2
0.5


In [ ]:
regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA__umid = 65

In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA__umid = 65

regiaoA_goiaba = regiaoA_temp * w1 + regiaoA_chuva * w2 + regiaoA__umid * w3
print("na regiao A a produçao de {} toneladas por hectare" . format(regiaoA_goiaba))

na regiao A a produçao de 52.5 toneladas por hectare


In [ ]:
regiaoA = [22, 67, 65]
regiaoB = [24, 88, 95]
regiaoC = [17, 134, 50]
regiaoD = [18, 96, 70]

pesos = [w1, w2, w3]

In [ ]:
nomes = ['alice' , 'bob','charlie']
idades = [25, 30 ,35]

lista_combinada = list(zip(nomes, idades))
print(lista_combinada)

[('alice', 25), ('bob', 30), ('charlie', 35)]


In [ ]:
def produçao_goiaba(regiao, pesos):
  result = 0
  for x, w in zip(regiao,pesos):
    result += x * w
  return result

In [ ]:
C

52.5


In [ ]:
print(produçao_goiaba(regiaoA, pesos))
print(produçao_goiaba(regiaoB, pesos))
print(produçao_goiaba(regiaoC, pesos))
print(produçao_goiaba(regiaoD, pesos))

52.5
72.3
56.9
59.6


In [ ]:
import numpy as np

regiaoA = np.array([22, 67, 65])

print(type(regiaoA))

pesos = np.array([w1, w2, w3])

print(type(pesos))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
reg_a = np.dot(regiaoA, pesos)
print('regiao A: {}'.format(reg_a))

regiao A: 52.5


In [ ]:
#lista em python
arr1 = list(range(2000000))
arr2 = list(range(1000000, 3000000))

#vetor em numpy
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
  result += x1*x2
print(result)

4666663666667000000
CPU times: user 404 ms, sys: 0 ns, total: 404 ms
Wall time: 405 ms


In [ ]:
%%time
print(np.dot(arr1_np, arr2_np))

4666663666667000000
CPU times: user 6.75 ms, sys: 0 ns, total: 6.75 ms
Wall time: 5.17 ms


In [ ]:
dados_climaticos =np.array([[22, 67, 65],
                  [24, 88, 95],
                   [17, 134, 50],
                  [18, 96, 70],])
print(dados_climaticos)

[[ 22  67  65]
 [ 24  88  95]
 [ 17 134  50]
 [ 18  96  70]]


In [ ]:
print(dados_climaticos.shape)

print(pesos.shape)

(4, 3)
(3,)


In [ ]:
print(pesos.dtype)
print('----------')
print(dados_climaticos.dtype)

float64
----------
int64


In [ ]:
dados_climaticos @ pesos

array([52.5, 72.3, 56.9, 59.6])

In [2]:
import numpy as np

camila_cvs = np.genfromtxt('/content/camila.csv', delimiter= ',')

In [3]:
camila_cvs

array([[23., 29., 95.],
       [24., 20., 21.],
       [18., 23., 16.],
       [19., 30., 36.]])

In [4]:
pesos = np.array([0.4, 0.2, 0.8])

In [5]:
rendimento = camila_cvs @ pesos

In [6]:
# incluir o resultado na regiao do array
resultado = np.concatenate((camila_cvs, rendimento.reshape(4,1)), axis=1)

In [7]:
resultado

array([[23. , 29. , 95. , 91. ],
       [24. , 20. , 21. , 30.4],
       [18. , 23. , 16. , 24.6],
       [19. , 30. , 36. , 42.4]])

In [14]:
#agora é so salvar
np.savetxt('camila_resultado.csv',
           resultado,
           fmt='%.2f',
           delimiter=',',
           header='temperatura,precipitação,umidade,rendimento',
           comments='')